# Generated by Django 3.2.7 on 2021-09-15 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flavours', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flavour',
            name='availability',
        ),
    ]
